// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recordcollection.proto

package recordcollection

import (
	fmt "fmt"
	godiscogs "github.com/brotherlogic/godiscogs"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Purgatory int32

const (
	Purgatory_UNKNOWN           Purgatory = 0
	Purgatory_NO_GOAL_FOLDER    Purgatory = 1
	Purgatory_NEEDS_STOCK_CHECK Purgatory = 2
	Purgatory_NEEDS_LABELS      Purgatory = 4
	Purgatory_NEEDS_RIP         Purgatory = 5
	Purgatory_ALL_GOOD          Purgatory = 3
)

var Purgatory_name = map[int32]string{
	0: "UNKNOWN",
	1: "NO_GOAL_FOLDER",
	2: "NEEDS_STOCK_CHECK",
	4: "NEEDS_LABELS",
	5: "NEEDS_RIP",
	3: "ALL_GOOD",
}

var Purgatory_value = map[string]int32{
	"UNKNOWN":           0,
	"NO_GOAL_FOLDER":    1,
	"NEEDS_STOCK_CHECK": 2,
	"NEEDS_LABELS":      4,
	"NEEDS_RIP":         5,
	"ALL_GOOD":          3,
}

func (x Purgatory) String() string {
	return proto.EnumName(Purgatory_name, int32(x))
}

func (Purgatory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{0}
}

type ReleaseMetadata_Category int32

const (
	ReleaseMetadata_UNKNOWN           ReleaseMetadata_Category = 0
	ReleaseMetadata_PURCHASED         ReleaseMetadata_Category = 1
	ReleaseMetadata_UNLISTENED        ReleaseMetadata_Category = 2
	ReleaseMetadata_STAGED            ReleaseMetadata_Category = 3
	ReleaseMetadata_PRE_HIGH_SCHOOL   ReleaseMetadata_Category = 25
	ReleaseMetadata_HIGH_SCHOOL       ReleaseMetadata_Category = 26
	ReleaseMetadata_PRE_FRESHMAN      ReleaseMetadata_Category = 4
	ReleaseMetadata_FRESHMAN          ReleaseMetadata_Category = 5
	ReleaseMetadata_PRE_SOPHMORE      ReleaseMetadata_Category = 12
	ReleaseMetadata_SOPHMORE          ReleaseMetadata_Category = 13
	ReleaseMetadata_PRE_GRADUATE      ReleaseMetadata_Category = 10
	ReleaseMetadata_GRADUATE          ReleaseMetadata_Category = 11
	ReleaseMetadata_PRE_POSTDOC       ReleaseMetadata_Category = 8
	ReleaseMetadata_POSTDOC           ReleaseMetadata_Category = 9
	ReleaseMetadata_PRE_PROFESSOR     ReleaseMetadata_Category = 6
	ReleaseMetadata_PROFESSOR         ReleaseMetadata_Category = 7
	ReleaseMetadata_PRE_DISTINGUISHED ReleaseMetadata_Category = 30
	ReleaseMetadata_DISTINGUISHED     ReleaseMetadata_Category = 31
	ReleaseMetadata_PREPARE_TO_SELL   ReleaseMetadata_Category = 19
	ReleaseMetadata_ASSESS_FOR_SALE   ReleaseMetadata_Category = 24
	ReleaseMetadata_STAGED_TO_SELL    ReleaseMetadata_Category = 14
	ReleaseMetadata_RIP_THEN_SELL     ReleaseMetadata_Category = 21
	ReleaseMetadata_SOLD              ReleaseMetadata_Category = 15
	ReleaseMetadata_SOLD_ARCHIVE      ReleaseMetadata_Category = 22
	ReleaseMetadata_LISTED_TO_SELL    ReleaseMetadata_Category = 23
	ReleaseMetadata_SOLD_OFFLINE      ReleaseMetadata_Category = 27
	ReleaseMetadata_STALE_SALE        ReleaseMetadata_Category = 28
	ReleaseMetadata_DIGITAL           ReleaseMetadata_Category = 16
	ReleaseMetadata_GOOGLE_PLAY       ReleaseMetadata_Category = 18
	ReleaseMetadata_ASSESS            ReleaseMetadata_Category = 17
	ReleaseMetadata_NO_LABELS         ReleaseMetadata_Category = 20
	ReleaseMetadata_PARENTS           ReleaseMetadata_Category = 29
)

var ReleaseMetadata_Category_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "PURCHASED",
	2:  "UNLISTENED",
	3:  "STAGED",
	25: "PRE_HIGH_SCHOOL",
	26: "HIGH_SCHOOL",
	4:  "PRE_FRESHMAN",
	5:  "FRESHMAN",
	12: "PRE_SOPHMORE",
	13: "SOPHMORE",
	10: "PRE_GRADUATE",
	11: "GRADUATE",
	8:  "PRE_POSTDOC",
	9:  "POSTDOC",
	6:  "PRE_PROFESSOR",
	7:  "PROFESSOR",
	30: "PRE_DISTINGUISHED",
	31: "DISTINGUISHED",
	19: "PREPARE_TO_SELL",
	24: "ASSESS_FOR_SALE",
	14: "STAGED_TO_SELL",
	21: "RIP_THEN_SELL",
	15: "SOLD",
	22: "SOLD_ARCHIVE",
	23: "LISTED_TO_SELL",
	27: "SOLD_OFFLINE",
	28: "STALE_SALE",
	16: "DIGITAL",
	18: "GOOGLE_PLAY",
	17: "ASSESS",
	20: "NO_LABELS",
	29: "PARENTS",
}

var ReleaseMetadata_Category_value = map[string]int32{
	"UNKNOWN":           0,
	"PURCHASED":         1,
	"UNLISTENED":        2,
	"STAGED":            3,
	"PRE_HIGH_SCHOOL":   25,
	"HIGH_SCHOOL":       26,
	"PRE_FRESHMAN":      4,
	"FRESHMAN":          5,
	"PRE_SOPHMORE":      12,
	"SOPHMORE":          13,
	"PRE_GRADUATE":      10,
	"GRADUATE":          11,
	"PRE_POSTDOC":       8,
	"POSTDOC":           9,
	"PRE_PROFESSOR":     6,
	"PROFESSOR":         7,
	"PRE_DISTINGUISHED": 30,
	"DISTINGUISHED":     31,
	"PREPARE_TO_SELL":   19,
	"ASSESS_FOR_SALE":   24,
	"STAGED_TO_SELL":    14,
	"RIP_THEN_SELL":     21,
	"SOLD":              15,
	"SOLD_ARCHIVE":      22,
	"LISTED_TO_SELL":    23,
	"SOLD_OFFLINE":      27,
	"STALE_SALE":        28,
	"DIGITAL":           16,
	"GOOGLE_PLAY":       18,
	"ASSESS":            17,
	"NO_LABELS":         20,
	"PARENTS":           29,
}

func (x ReleaseMetadata_Category) String() string {
	return proto.EnumName(ReleaseMetadata_Category_name, int32(x))
}

func (ReleaseMetadata_Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{5, 0}
}

type ReleaseMetadata_KeepState int32

const (
	ReleaseMetadata_KEEP_UNKNOWN ReleaseMetadata_KeepState = 0
	ReleaseMetadata_NOT_KEEPER   ReleaseMetadata_KeepState = 1
	ReleaseMetadata_KEEPER       ReleaseMetadata_KeepState = 2
)

var ReleaseMetadata_KeepState_name = map[int32]string{
	0: "KEEP_UNKNOWN",
	1: "NOT_KEEPER",
	2: "KEEPER",
}

var ReleaseMetadata_KeepState_value = map[string]int32{
	"KEEP_UNKNOWN": 0,
	"NOT_KEEPER":   1,
	"KEEPER":       2,
}

func (x ReleaseMetadata_KeepState) String() string {
	return proto.EnumName(ReleaseMetadata_KeepState_name, int32(x))
}

func (ReleaseMetadata_KeepState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{5, 1}
}

type ReleaseMetadata_MatchState int32

const (
	ReleaseMetadata_MATCH_UNKNOWN ReleaseMetadata_MatchState = 0
	ReleaseMetadata_NO_MATCH      ReleaseMetadata_MatchState = 1
	ReleaseMetadata_PARTIAL_MATCH ReleaseMetadata_MatchState = 2
	ReleaseMetadata_FULL_MATCH    ReleaseMetadata_MatchState = 3
)

var ReleaseMetadata_MatchState_name = map[int32]string{
	0: "MATCH_UNKNOWN",
	1: "NO_MATCH",
	2: "PARTIAL_MATCH",
	3: "FULL_MATCH",
}

var ReleaseMetadata_MatchState_value = map[string]int32{
	"MATCH_UNKNOWN": 0,
	"NO_MATCH":      1,
	"PARTIAL_MATCH": 2,
	"FULL_MATCH":    3,
}

func (x ReleaseMetadata_MatchState) String() string {
	return proto.EnumName(ReleaseMetadata_MatchState_name, int32(x))
}

func (ReleaseMetadata_MatchState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{5, 2}
}

type RecordCollection struct {
	Records              []*Record            `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Wants                []*godiscogs.Release `protobuf:"bytes,2,rep,name=wants,proto3" json:"wants,omitempty"`
	NewWants             []*Want              `protobuf:"bytes,3,rep,name=new_wants,json=newWants,proto3" json:"new_wants,omitempty"`
	Instances            []int32              `protobuf:"varint,4,rep,packed,name=instances,proto3" json:"instances,omitempty"`
	CollectionNumber     int64                `protobuf:"varint,5,opt,name=collection_number,json=collectionNumber,proto3" json:"collection_number,omitempty"`
	InstanceToFolder     map[int32]int32      `protobuf:"bytes,6,rep,name=instance_to_folder,json=instanceToFolder,proto3" json:"instance_to_folder,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecordCollection) Reset()         { *m = RecordCollection{} }
func (m *RecordCollection) String() string { return proto.CompactTextString(m) }
func (*RecordCollection) ProtoMessage()    {}
func (*RecordCollection) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{0}
}

func (m *RecordCollection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordCollection.Unmarshal(m, b)
}
func (m *RecordCollection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordCollection.Marshal(b, m, deterministic)
}
func (m *RecordCollection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordCollection.Merge(m, src)
}
func (m *RecordCollection) XXX_Size() int {
	return xxx_messageInfo_RecordCollection.Size(m)
}
func (m *RecordCollection) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordCollection.DiscardUnknown(m)
}

var xxx_messageInfo_RecordCollection proto.InternalMessageInfo

func (m *RecordCollection) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *RecordCollection) GetWants() []*godiscogs.Release {
	if m != nil {
		return m.Wants
	}
	return nil
}

func (m *RecordCollection) GetNewWants() []*Want {
	if m != nil {
		return m.NewWants
	}
	return nil
}

func (m *RecordCollection) GetInstances() []int32 {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *RecordCollection) GetCollectionNumber() int64 {
	if m != nil {
		return m.CollectionNumber
	}
	return 0
}

func (m *RecordCollection) GetInstanceToFolder() map[int32]int32 {
	if m != nil {
		return m.InstanceToFolder
	}
	return nil
}

// This is a record that we own
type Record struct {
	Release              *godiscogs.Release `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Metadata             *ReleaseMetadata   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{1}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetRelease() *godiscogs.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *Record) GetMetadata() *ReleaseMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Want struct {
	Release  *godiscogs.Release `protobuf:"bytes,1,opt,name=release,proto3" json:"release,omitempty"`
	Metadata *WantMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Delete this want
	ClearWant            bool     `protobuf:"varint,3,opt,name=clear_want,json=clearWant,proto3" json:"clear_want,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Want) Reset()         { *m = Want{} }
func (m *Want) String() string { return proto.CompactTextString(m) }
func (*Want) ProtoMessage()    {}
func (*Want) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{2}
}

func (m *Want) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Want.Unmarshal(m, b)
}
func (m *Want) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Want.Marshal(b, m, deterministic)
}
func (m *Want) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Want.Merge(m, src)
}
func (m *Want) XXX_Size() int {
	return xxx_messageInfo_Want.Size(m)
}
func (m *Want) XXX_DiscardUnknown() {
	xxx_messageInfo_Want.DiscardUnknown(m)
}

var xxx_messageInfo_Want proto.InternalMessageInfo

func (m *Want) GetRelease() *godiscogs.Release {
	if m != nil {
		return m.Release
	}
	return nil
}

func (m *Want) GetMetadata() *WantMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Want) GetClearWant() bool {
	if m != nil {
		return m.ClearWant
	}
	return false
}

type WantMetadata struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WantMetadata) Reset()         { *m = WantMetadata{} }
func (m *WantMetadata) String() string { return proto.CompactTextString(m) }
func (*WantMetadata) ProtoMessage()    {}
func (*WantMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{3}
}

func (m *WantMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WantMetadata.Unmarshal(m, b)
}
func (m *WantMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WantMetadata.Marshal(b, m, deterministic)
}
func (m *WantMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WantMetadata.Merge(m, src)
}
func (m *WantMetadata) XXX_Size() int {
	return xxx_messageInfo_WantMetadata.Size(m)
}
func (m *WantMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_WantMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_WantMetadata proto.InternalMessageInfo

func (m *WantMetadata) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

// This is the discogs token
type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{4}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ReleaseMetadata struct {
	// The date the release was added
	DateAdded int64 `protobuf:"varint,1,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`
	// The date the release was last updated
	DateUpdated int64 `protobuf:"varint,2,opt,name=date_updated,json=dateUpdated,proto3" json:"date_updated,omitempty"`
	// The relative path to the release
	FilePath string `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	// The cost of the record in cents
	Cost int32 `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	// If we have other copies of this
	Others bool `protobuf:"varint,5,opt,name=others,proto3" json:"others,omitempty"`
	// The id of the release this relates to
	Id int32 `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	// The data we last recached this release
	LastCache int64                    `protobuf:"varint,7,opt,name=last_cache,json=lastCache,proto3" json:"last_cache,omitempty"`
	Category  ReleaseMetadata_Category `protobuf:"varint,8,opt,name=category,proto3,enum=recordcollection.ReleaseMetadata_Category" json:"category,omitempty"`
	// The folder this record should be placed in
	GoalFolder int32 `protobuf:"varint,9,opt,name=goal_folder,json=goalFolder,proto3" json:"goal_folder,omitempty"`
	// If a record is dirty, it needs to send updates to discogs
	Dirty bool `protobuf:"varint,10,opt,name=dirty,proto3" json:"dirty,omitempty"`
	// The folder this record should move to
	MoveFolder int32 `protobuf:"varint,11,opt,name=move_folder,json=moveFolder,proto3" json:"move_folder,omitempty"`
	// This is the rating that should be set on the record
	SetRating int32 `protobuf:"varint,12,opt,name=set_rating,json=setRating,proto3" json:"set_rating,omitempty"`
	// The time we were last Synced
	LastSyncTime int64     `protobuf:"varint,13,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	Purgatory    Purgatory `protobuf:"varint,14,opt,name=purgatory,proto3,enum=recordcollection.Purgatory" json:"purgatory,omitempty"`
	// The last time we did a stock check
	LastStockCheck int64 `protobuf:"varint,15,opt,name=last_stock_check,json=lastStockCheck,proto3" json:"last_stock_check,omitempty"`
	// This is an overall score
	OverallScore float32 `protobuf:"fixed32,16,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	// Width of spine in mm
	SpineWidth int32 `protobuf:"varint,17,opt,name=spine_width,json=spineWidth,proto3" json:"spine_width,omitempty"`
	// Sale cost and ID if applicable
	SaleCost  int32               `protobuf:"varint,18,opt,name=sale_cost,json=saleCost,proto3" json:"sale_cost,omitempty"`
	SaleId    int32               `protobuf:"varint,19,opt,name=sale_id,json=saleId,proto3" json:"sale_id,omitempty"`
	SaleDirty bool                `protobuf:"varint,21,opt,name=sale_dirty,json=saleDirty,proto3" json:"sale_dirty,omitempty"`
	SalePrice int32               `protobuf:"varint,22,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"`
	SaleState godiscogs.SaleState `protobuf:"varint,23,opt,name=sale_state,json=saleState,proto3,enum=godiscogs.SaleState" json:"sale_state,omitempty"`
	// Reason for a move failure
	MoveFailure string `protobuf:"bytes,20,opt,name=move_failure,json=moveFailure,proto3" json:"move_failure,omitempty"`
	// The last time we were listened to
	LastListenTime int64 `protobuf:"varint,24,opt,name=last_listen_time,json=lastListenTime,proto3" json:"last_listen_time,omitempty"`
	// The path to cd rip of this record
	CdPath string `protobuf:"bytes,25,opt,name=cd_path,json=cdPath,proto3" json:"cd_path,omitempty"`
	// The time we last moved this record
	LastMoveTime int64 `protobuf:"varint,26,opt,name=last_move_time,json=lastMoveTime,proto3" json:"last_move_time,omitempty"`
	// Ref to the release instance id
	InstanceId int32 `protobuf:"varint,27,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// If we need to stock check this record
	NeedsStockCheck      bool                       `protobuf:"varint,28,opt,name=needs_stock_check,json=needsStockCheck,proto3" json:"needs_stock_check,omitempty"`
	Keep                 ReleaseMetadata_KeepState  `protobuf:"varint,29,opt,name=keep,proto3,enum=recordcollection.ReleaseMetadata_KeepState" json:"keep,omitempty"`
	Match                ReleaseMetadata_MatchState `protobuf:"varint,30,opt,name=match,proto3,enum=recordcollection.ReleaseMetadata_MatchState" json:"match,omitempty"`
	CurrentSalePrice     int32                      `protobuf:"varint,31,opt,name=current_sale_price,json=currentSalePrice,proto3" json:"current_sale_price,omitempty"`
	SalePriceUpdate      int64                      `protobuf:"varint,32,opt,name=sale_price_update,json=salePriceUpdate,proto3" json:"sale_price_update,omitempty"`
	LastSaveTime         int64                      `protobuf:"varint,33,opt,name=last_save_time,json=lastSaveTime,proto3" json:"last_save_time,omitempty"`
	SaveIteration        int64                      `protobuf:"varint,34,opt,name=save_iteration,json=saveIteration,proto3" json:"save_iteration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ReleaseMetadata) Reset()         { *m = ReleaseMetadata{} }
func (m *ReleaseMetadata) String() string { return proto.CompactTextString(m) }
func (*ReleaseMetadata) ProtoMessage()    {}
func (*ReleaseMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{5}
}

func (m *ReleaseMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReleaseMetadata.Unmarshal(m, b)
}
func (m *ReleaseMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReleaseMetadata.Marshal(b, m, deterministic)
}
func (m *ReleaseMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseMetadata.Merge(m, src)
}
func (m *ReleaseMetadata) XXX_Size() int {
	return xxx_messageInfo_ReleaseMetadata.Size(m)
}
func (m *ReleaseMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseMetadata proto.InternalMessageInfo

func (m *ReleaseMetadata) GetDateAdded() int64 {
	if m != nil {
		return m.DateAdded
	}
	return 0
}

func (m *ReleaseMetadata) GetDateUpdated() int64 {
	if m != nil {
		return m.DateUpdated
	}
	return 0
}

func (m *ReleaseMetadata) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func (m *ReleaseMetadata) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *ReleaseMetadata) GetOthers() bool {
	if m != nil {
		return m.Others
	}
	return false
}

func (m *ReleaseMetadata) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReleaseMetadata) GetLastCache() int64 {
	if m != nil {
		return m.LastCache
	}
	return 0
}

func (m *ReleaseMetadata) GetCategory() ReleaseMetadata_Category {
	if m != nil {
		return m.Category
	}
	return ReleaseMetadata_UNKNOWN
}

func (m *ReleaseMetadata) GetGoalFolder() int32 {
	if m != nil {
		return m.GoalFolder
	}
	return 0
}

func (m *ReleaseMetadata) GetDirty() bool {
	if m != nil {
		return m.Dirty
	}
	return false
}

func (m *ReleaseMetadata) GetMoveFolder() int32 {
	if m != nil {
		return m.MoveFolder
	}
	return 0
}

func (m *ReleaseMetadata) GetSetRating() int32 {
	if m != nil {
		return m.SetRating
	}
	return 0
}

func (m *ReleaseMetadata) GetLastSyncTime() int64 {
	if m != nil {
		return m.LastSyncTime
	}
	return 0
}

func (m *ReleaseMetadata) GetPurgatory() Purgatory {
	if m != nil {
		return m.Purgatory
	}
	return Purgatory_UNKNOWN
}

func (m *ReleaseMetadata) GetLastStockCheck() int64 {
	if m != nil {
		return m.LastStockCheck
	}
	return 0
}

func (m *ReleaseMetadata) GetOverallScore() float32 {
	if m != nil {
		return m.OverallScore
	}
	return 0
}

func (m *ReleaseMetadata) GetSpineWidth() int32 {
	if m != nil {
		return m.SpineWidth
	}
	return 0
}

func (m *ReleaseMetadata) GetSaleCost() int32 {
	if m != nil {
		return m.SaleCost
	}
	return 0
}

func (m *ReleaseMetadata) GetSaleId() int32 {
	if m != nil {
		return m.SaleId
	}
	return 0
}

func (m *ReleaseMetadata) GetSaleDirty() bool {
	if m != nil {
		return m.SaleDirty
	}
	return false
}

func (m *ReleaseMetadata) GetSalePrice() int32 {
	if m != nil {
		return m.SalePrice
	}
	return 0
}

func (m *ReleaseMetadata) GetSaleState() godiscogs.SaleState {
	if m != nil {
		return m.SaleState
	}
	return godiscogs.SaleState_NOT_FOR_SALE
}

func (m *ReleaseMetadata) GetMoveFailure() string {
	if m != nil {
		return m.MoveFailure
	}
	return ""
}

func (m *ReleaseMetadata) GetLastListenTime() int64 {
	if m != nil {
		return m.LastListenTime
	}
	return 0
}

func (m *ReleaseMetadata) GetCdPath() string {
	if m != nil {
		return m.CdPath
	}
	return ""
}

func (m *ReleaseMetadata) GetLastMoveTime() int64 {
	if m != nil {
		return m.LastMoveTime
	}
	return 0
}

func (m *ReleaseMetadata) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

func (m *ReleaseMetadata) GetNeedsStockCheck() bool {
	if m != nil {
		return m.NeedsStockCheck
	}
	return false
}

func (m *ReleaseMetadata) GetKeep() ReleaseMetadata_KeepState {
	if m != nil {
		return m.Keep
	}
	return ReleaseMetadata_KEEP_UNKNOWN
}

func (m *ReleaseMetadata) GetMatch() ReleaseMetadata_MatchState {
	if m != nil {
		return m.Match
	}
	return ReleaseMetadata_MATCH_UNKNOWN
}

func (m *ReleaseMetadata) GetCurrentSalePrice() int32 {
	if m != nil {
		return m.CurrentSalePrice
	}
	return 0
}

func (m *ReleaseMetadata) GetSalePriceUpdate() int64 {
	if m != nil {
		return m.SalePriceUpdate
	}
	return 0
}

func (m *ReleaseMetadata) GetLastSaveTime() int64 {
	if m != nil {
		return m.LastSaveTime
	}
	return 0
}

func (m *ReleaseMetadata) GetSaveIteration() int64 {
	if m != nil {
		return m.SaveIteration
	}
	return 0
}

// A request to get some records
type GetRecordsRequest struct {
	Filter *Record `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// DEPRECATED
	Force bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	// Return a stripped response
	Strip bool `protobuf:"varint,3,opt,name=strip,proto3" json:"strip,omitempty"`
	// Strip out for record mover
	MoveStrip bool `protobuf:"varint,4,opt,name=move_strip,json=moveStrip,proto3" json:"move_strip,omitempty"`
	// Reference the caller
	Caller               string   `protobuf:"bytes,5,opt,name=caller,proto3" json:"caller,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordsRequest) Reset()         { *m = GetRecordsRequest{} }
func (m *GetRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecordsRequest) ProtoMessage()    {}
func (*GetRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{6}
}

func (m *GetRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordsRequest.Unmarshal(m, b)
}
func (m *GetRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordsRequest.Marshal(b, m, deterministic)
}
func (m *GetRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordsRequest.Merge(m, src)
}
func (m *GetRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecordsRequest.Size(m)
}
func (m *GetRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordsRequest proto.InternalMessageInfo

func (m *GetRecordsRequest) GetFilter() *Record {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *GetRecordsRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

func (m *GetRecordsRequest) GetStrip() bool {
	if m != nil {
		return m.Strip
	}
	return false
}

func (m *GetRecordsRequest) GetMoveStrip() bool {
	if m != nil {
		return m.MoveStrip
	}
	return false
}

func (m *GetRecordsRequest) GetCaller() string {
	if m != nil {
		return m.Caller
	}
	return ""
}

// A list of records in response
type GetRecordsResponse struct {
	Records                []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	InternalProcessingTime int64     `protobuf:"varint,2,opt,name=internal_processing_time,json=internalProcessingTime,proto3" json:"internal_processing_time,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}  `json:"-"`
	XXX_unrecognized       []byte    `json:"-"`
	XXX_sizecache          int32     `json:"-"`
}

func (m *GetRecordsResponse) Reset()         { *m = GetRecordsResponse{} }
func (m *GetRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecordsResponse) ProtoMessage()    {}
func (*GetRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{7}
}

func (m *GetRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordsResponse.Unmarshal(m, b)
}
func (m *GetRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordsResponse.Marshal(b, m, deterministic)
}
func (m *GetRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordsResponse.Merge(m, src)
}
func (m *GetRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecordsResponse.Size(m)
}
func (m *GetRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordsResponse proto.InternalMessageInfo

func (m *GetRecordsResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *GetRecordsResponse) GetInternalProcessingTime() int64 {
	if m != nil {
		return m.InternalProcessingTime
	}
	return 0
}

// A request to get some records
type GetWantsRequest struct {
	Filter               *Want    `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWantsRequest) Reset()         { *m = GetWantsRequest{} }
func (m *GetWantsRequest) String() string { return proto.CompactTextString(m) }
func (*GetWantsRequest) ProtoMessage()    {}
func (*GetWantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{8}
}

func (m *GetWantsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWantsRequest.Unmarshal(m, b)
}
func (m *GetWantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWantsRequest.Marshal(b, m, deterministic)
}
func (m *GetWantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWantsRequest.Merge(m, src)
}
func (m *GetWantsRequest) XXX_Size() int {
	return xxx_messageInfo_GetWantsRequest.Size(m)
}
func (m *GetWantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWantsRequest proto.InternalMessageInfo

func (m *GetWantsRequest) GetFilter() *Want {
	if m != nil {
		return m.Filter
	}
	return nil
}

// A list of records in response
type GetWantsResponse struct {
	Wants                []*Want  `protobuf:"bytes,1,rep,name=wants,proto3" json:"wants,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWantsResponse) Reset()         { *m = GetWantsResponse{} }
func (m *GetWantsResponse) String() string { return proto.CompactTextString(m) }
func (*GetWantsResponse) ProtoMessage()    {}
func (*GetWantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{9}
}

func (m *GetWantsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWantsResponse.Unmarshal(m, b)
}
func (m *GetWantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWantsResponse.Marshal(b, m, deterministic)
}
func (m *GetWantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWantsResponse.Merge(m, src)
}
func (m *GetWantsResponse) XXX_Size() int {
	return xxx_messageInfo_GetWantsResponse.Size(m)
}
func (m *GetWantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWantsResponse proto.InternalMessageInfo

func (m *GetWantsResponse) GetWants() []*Want {
	if m != nil {
		return m.Wants
	}
	return nil
}

type UpdateRecordRequest struct {
	Update               *Record  `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	Requestor            string   `protobuf:"bytes,2,opt,name=requestor,proto3" json:"requestor,omitempty"`
	NoSell               bool     `protobuf:"varint,3,opt,name=no_sell,json=noSell,proto3" json:"no_sell,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecordRequest) Reset()         { *m = UpdateRecordRequest{} }
func (m *UpdateRecordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRecordRequest) ProtoMessage()    {}
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{10}
}

func (m *UpdateRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecordRequest.Unmarshal(m, b)
}
func (m *UpdateRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecordRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecordRequest.Merge(m, src)
}
func (m *UpdateRecordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRecordRequest.Size(m)
}
func (m *UpdateRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecordRequest proto.InternalMessageInfo

func (m *UpdateRecordRequest) GetUpdate() *Record {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *UpdateRecordRequest) GetRequestor() string {
	if m != nil {
		return m.Requestor
	}
	return ""
}

func (m *UpdateRecordRequest) GetNoSell() bool {
	if m != nil {
		return m.NoSell
	}
	return false
}

type UpdateRecordsResponse struct {
	Updated              *Record  `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRecordsResponse) Reset()         { *m = UpdateRecordsResponse{} }
func (m *UpdateRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRecordsResponse) ProtoMessage()    {}
func (*UpdateRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{11}
}

func (m *UpdateRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRecordsResponse.Unmarshal(m, b)
}
func (m *UpdateRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRecordsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRecordsResponse.Merge(m, src)
}
func (m *UpdateRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRecordsResponse.Size(m)
}
func (m *UpdateRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRecordsResponse proto.InternalMessageInfo

func (m *UpdateRecordsResponse) GetUpdated() *Record {
	if m != nil {
		return m.Updated
	}
	return nil
}

type UpdateWantRequest struct {
	Update               *Want    `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	Remove               bool     `protobuf:"varint,2,opt,name=remove,proto3" json:"remove,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWantRequest) Reset()         { *m = UpdateWantRequest{} }
func (m *UpdateWantRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateWantRequest) ProtoMessage()    {}
func (*UpdateWantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{12}
}

func (m *UpdateWantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWantRequest.Unmarshal(m, b)
}
func (m *UpdateWantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWantRequest.Marshal(b, m, deterministic)
}
func (m *UpdateWantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWantRequest.Merge(m, src)
}
func (m *UpdateWantRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateWantRequest.Size(m)
}
func (m *UpdateWantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWantRequest proto.InternalMessageInfo

func (m *UpdateWantRequest) GetUpdate() *Want {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *UpdateWantRequest) GetRemove() bool {
	if m != nil {
		return m.Remove
	}
	return false
}

type UpdateWantResponse struct {
	Updated              *Want    `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateWantResponse) Reset()         { *m = UpdateWantResponse{} }
func (m *UpdateWantResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateWantResponse) ProtoMessage()    {}
func (*UpdateWantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{13}
}

func (m *UpdateWantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateWantResponse.Unmarshal(m, b)
}
func (m *UpdateWantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateWantResponse.Marshal(b, m, deterministic)
}
func (m *UpdateWantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateWantResponse.Merge(m, src)
}
func (m *UpdateWantResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateWantResponse.Size(m)
}
func (m *UpdateWantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateWantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateWantResponse proto.InternalMessageInfo

func (m *UpdateWantResponse) GetUpdated() *Want {
	if m != nil {
		return m.Updated
	}
	return nil
}

type AddRecordRequest struct {
	ToAdd                *Record  `protobuf:"bytes,1,opt,name=to_add,json=toAdd,proto3" json:"to_add,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRecordRequest) Reset()         { *m = AddRecordRequest{} }
func (m *AddRecordRequest) String() string { return proto.CompactTextString(m) }
func (*AddRecordRequest) ProtoMessage()    {}
func (*AddRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{14}
}

func (m *AddRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRecordRequest.Unmarshal(m, b)
}
func (m *AddRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRecordRequest.Marshal(b, m, deterministic)
}
func (m *AddRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRecordRequest.Merge(m, src)
}
func (m *AddRecordRequest) XXX_Size() int {
	return xxx_messageInfo_AddRecordRequest.Size(m)
}
func (m *AddRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRecordRequest proto.InternalMessageInfo

func (m *AddRecordRequest) GetToAdd() *Record {
	if m != nil {
		return m.ToAdd
	}
	return nil
}

type AddRecordResponse struct {
	Added                *Record  `protobuf:"bytes,2,opt,name=added,proto3" json:"added,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRecordResponse) Reset()         { *m = AddRecordResponse{} }
func (m *AddRecordResponse) String() string { return proto.CompactTextString(m) }
func (*AddRecordResponse) ProtoMessage()    {}
func (*AddRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{15}
}

func (m *AddRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRecordResponse.Unmarshal(m, b)
}
func (m *AddRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRecordResponse.Marshal(b, m, deterministic)
}
func (m *AddRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRecordResponse.Merge(m, src)
}
func (m *AddRecordResponse) XXX_Size() int {
	return xxx_messageInfo_AddRecordResponse.Size(m)
}
func (m *AddRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRecordResponse proto.InternalMessageInfo

func (m *AddRecordResponse) GetAdded() *Record {
	if m != nil {
		return m.Added
	}
	return nil
}

type GetRecordCollectionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordCollectionRequest) Reset()         { *m = GetRecordCollectionRequest{} }
func (m *GetRecordCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecordCollectionRequest) ProtoMessage()    {}
func (*GetRecordCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{16}
}

func (m *GetRecordCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordCollectionRequest.Unmarshal(m, b)
}
func (m *GetRecordCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordCollectionRequest.Marshal(b, m, deterministic)
}
func (m *GetRecordCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordCollectionRequest.Merge(m, src)
}
func (m *GetRecordCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecordCollectionRequest.Size(m)
}
func (m *GetRecordCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordCollectionRequest proto.InternalMessageInfo

type GetRecordCollectionResponse struct {
	InstanceIds          []int32  `protobuf:"varint,1,rep,packed,name=instance_ids,json=instanceIds,proto3" json:"instance_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecordCollectionResponse) Reset()         { *m = GetRecordCollectionResponse{} }
func (m *GetRecordCollectionResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecordCollectionResponse) ProtoMessage()    {}
func (*GetRecordCollectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{17}
}

func (m *GetRecordCollectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecordCollectionResponse.Unmarshal(m, b)
}
func (m *GetRecordCollectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecordCollectionResponse.Marshal(b, m, deterministic)
}
func (m *GetRecordCollectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecordCollectionResponse.Merge(m, src)
}
func (m *GetRecordCollectionResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecordCollectionResponse.Size(m)
}
func (m *GetRecordCollectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecordCollectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecordCollectionResponse proto.InternalMessageInfo

func (m *GetRecordCollectionResponse) GetInstanceIds() []int32 {
	if m != nil {
		return m.InstanceIds
	}
	return nil
}

type DeleteRecordRequest struct {
	InstanceId           int32    `protobuf:"varint,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecordRequest) Reset()         { *m = DeleteRecordRequest{} }
func (m *DeleteRecordRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRecordRequest) ProtoMessage()    {}
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{18}
}

func (m *DeleteRecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecordRequest.Unmarshal(m, b)
}
func (m *DeleteRecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecordRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecordRequest.Merge(m, src)
}
func (m *DeleteRecordRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRecordRequest.Size(m)
}
func (m *DeleteRecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecordRequest proto.InternalMessageInfo

func (m *DeleteRecordRequest) GetInstanceId() int32 {
	if m != nil {
		return m.InstanceId
	}
	return 0
}

type DeleteRecordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRecordResponse) Reset()         { *m = DeleteRecordResponse{} }
func (m *DeleteRecordResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRecordResponse) ProtoMessage()    {}
func (*DeleteRecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{19}
}

func (m *DeleteRecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRecordResponse.Unmarshal(m, b)
}
func (m *DeleteRecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRecordResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRecordResponse.Merge(m, src)
}
func (m *DeleteRecordResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRecordResponse.Size(m)
}
func (m *DeleteRecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRecordResponse proto.InternalMessageInfo

type QueryRecordsRequest struct {
	// Types that are valid to be assigned to Query:
	//	*QueryRecordsRequest_FolderId
	Query                isQueryRecordsRequest_Query `protobuf_oneof:"query"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *QueryRecordsRequest) Reset()         { *m = QueryRecordsRequest{} }
func (m *QueryRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRecordsRequest) ProtoMessage()    {}
func (*QueryRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{20}
}

func (m *QueryRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRecordsRequest.Unmarshal(m, b)
}
func (m *QueryRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRecordsRequest.Marshal(b, m, deterministic)
}
func (m *QueryRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecordsRequest.Merge(m, src)
}
func (m *QueryRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRecordsRequest.Size(m)
}
func (m *QueryRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecordsRequest proto.InternalMessageInfo

type isQueryRecordsRequest_Query interface {
	isQueryRecordsRequest_Query()
}

type QueryRecordsRequest_FolderId struct {
	FolderId int32 `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3,oneof"`
}

func (*QueryRecordsRequest_FolderId) isQueryRecordsRequest_Query() {}

func (m *QueryRecordsRequest) GetQuery() isQueryRecordsRequest_Query {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *QueryRecordsRequest) GetFolderId() int32 {
	if x, ok := m.GetQuery().(*QueryRecordsRequest_FolderId); ok {
		return x.FolderId
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*QueryRecordsRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _QueryRecordsRequest_OneofMarshaler, _QueryRecordsRequest_OneofUnmarshaler, _QueryRecordsRequest_OneofSizer, []interface{}{
		(*QueryRecordsRequest_FolderId)(nil),
	}
}

func _QueryRecordsRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*QueryRecordsRequest)
	// query
	switch x := m.Query.(type) {
	case *QueryRecordsRequest_FolderId:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.FolderId))
	case nil:
	default:
		return fmt.Errorf("QueryRecordsRequest.Query has unexpected type %T", x)
	}
	return nil
}

func _QueryRecordsRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*QueryRecordsRequest)
	switch tag {
	case 1: // query.folder_id
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Query = &QueryRecordsRequest_FolderId{int32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _QueryRecordsRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*QueryRecordsRequest)
	// query
	switch x := m.Query.(type) {
	case *QueryRecordsRequest_FolderId:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.FolderId))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type QueryRecordsResponse struct {
	InstanceIds          []int32  `protobuf:"varint,1,rep,packed,name=instance_ids,json=instanceIds,proto3" json:"instance_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRecordsResponse) Reset()         { *m = QueryRecordsResponse{} }
func (m *QueryRecordsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRecordsResponse) ProtoMessage()    {}
func (*QueryRecordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdb41e27df802155, []int{21}
}

func (m *QueryRecordsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRecordsResponse.Unmarshal(m, b)
}
func (m *QueryRecordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRecordsResponse.Marshal(b, m, deterministic)
}
func (m *QueryRecordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecordsResponse.Merge(m, src)
}
func (m *QueryRecordsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryRecordsResponse.Size(m)
}
func (m *QueryRecordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecordsResponse proto.InternalMessageInfo

func (m *QueryRecordsResponse) GetInstanceIds() []int32 {
	if m != nil {
		return m.InstanceIds
	}
	return nil
}

func init() {
	proto.RegisterEnum("recordcollection.Purgatory", Purgatory_name, Purgatory_value)
	proto.RegisterEnum("recordcollection.ReleaseMetadata_Category", ReleaseMetadata_Category_name, ReleaseMetadata_Category_value)
	proto.RegisterEnum("recordcollection.ReleaseMetadata_KeepState", ReleaseMetadata_KeepState_name, ReleaseMetadata_KeepState_value)
	proto.RegisterEnum("recordcollection.ReleaseMetadata_MatchState", ReleaseMetadata_MatchState_name, ReleaseMetadata_MatchState_value)
	proto.RegisterType((*RecordCollection)(nil), "recordcollection.RecordCollection")
	proto.RegisterMapType((map[int32]int32)(nil), "recordcollection.RecordCollection.InstanceToFolderEntry")
	proto.RegisterType((*Record)(nil), "recordcollection.Record")
	proto.RegisterType((*Want)(nil), "recordcollection.Want")
	proto.RegisterType((*WantMetadata)(nil), "recordcollection.WantMetadata")
	proto.RegisterType((*Token)(nil), "recordcollection.Token")
	proto.RegisterType((*ReleaseMetadata)(nil), "recordcollection.ReleaseMetadata")
	proto.RegisterType((*GetRecordsRequest)(nil), "recordcollection.GetRecordsRequest")
	proto.RegisterType((*GetRecordsResponse)(nil), "recordcollection.GetRecordsResponse")
	proto.RegisterType((*GetWantsRequest)(nil), "recordcollection.GetWantsRequest")
	proto.RegisterType((*GetWantsResponse)(nil), "recordcollection.GetWantsResponse")
	proto.RegisterType((*UpdateRecordRequest)(nil), "recordcollection.UpdateRecordRequest")
	proto.RegisterType((*UpdateRecordsResponse)(nil), "recordcollection.UpdateRecordsResponse")
	proto.RegisterType((*UpdateWantRequest)(nil), "recordcollection.UpdateWantRequest")
	proto.RegisterType((*UpdateWantResponse)(nil), "recordcollection.UpdateWantResponse")
	proto.RegisterType((*AddRecordRequest)(nil), "recordcollection.AddRecordRequest")
	proto.RegisterType((*AddRecordResponse)(nil), "recordcollection.AddRecordResponse")
	proto.RegisterType((*GetRecordCollectionRequest)(nil), "recordcollection.GetRecordCollectionRequest")
	proto.RegisterType((*GetRecordCollectionResponse)(nil), "recordcollection.GetRecordCollectionResponse")
	proto.RegisterType((*DeleteRecordRequest)(nil), "recordcollection.DeleteRecordRequest")
	proto.RegisterType((*DeleteRecordResponse)(nil), "recordcollection.DeleteRecordResponse")
	proto.RegisterType((*QueryRecordsRequest)(nil), "recordcollection.QueryRecordsRequest")
	proto.RegisterType((*QueryRecordsResponse)(nil), "recordcollection.QueryRecordsResponse")
}

func init() { proto.RegisterFile("recordcollection.proto", fileDescriptor_fdb41e27df802155) }

var fileDescriptor_fdb41e27df802155 = []byte{
	// 1996 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0x4b, 0x73, 0xdb, 0xc8,
	0x11, 0x36, 0x9f, 0x22, 0x9b, 0x14, 0x05, 0x8e, 0x1e, 0xc6, 0xd2, 0x96, 0x2d, 0xc3, 0xbb, 0x1b,
	0x95, 0xd7, 0x91, 0x37, 0x76, 0x55, 0xca, 0xde, 0xaa, 0xad, 0x2c, 0x4c, 0x82, 0x8f, 0x12, 0x44,
	0x30, 0x03, 0x6a, 0x5d, 0xae, 0x1c, 0x10, 0x18, 0x18, 0x4b, 0x28, 0x41, 0x00, 0x17, 0x18, 0xca,
	0xa5, 0x4b, 0x0e, 0xf9, 0x03, 0xb9, 0xe5, 0x92, 0xca, 0x3d, 0x3f, 0x20, 0x3f, 0x30, 0x35, 0x33,
	0x78, 0x50, 0x24, 0x25, 0x6d, 0xf6, 0x64, 0xf4, 0xd7, 0xef, 0xee, 0xe9, 0x66, 0x5b, 0xb0, 0x17,
	0x11, 0x27, 0x8c, 0x5c, 0x27, 0xf4, 0x7d, 0xe2, 0x50, 0x2f, 0x0c, 0x8e, 0x66, 0x51, 0x48, 0x43,
	0x24, 0x2d, 0xe3, 0x9d, 0x3f, 0x9c, 0x79, 0xf4, 0x7c, 0xfe, 0xe9, 0xc8, 0x09, 0x2f, 0x5f, 0x7d,
	0x8a, 0x42, 0x7a, 0x4e, 0x22, 0x3f, 0x3c, 0xf3, 0x9c, 0x57, 0x67, 0xa1, 0xeb, 0xc5, 0x4e, 0x78,
	0x16, 0xe7, 0x5f, 0xc2, 0x88, 0xf2, 0xef, 0x12, 0x48, 0x98, 0xdb, 0xe9, 0x66, 0x76, 0xd0, 0x6b,
	0xd8, 0x10, 0xb6, 0x63, 0xb9, 0x70, 0x50, 0x3a, 0x6c, 0xbc, 0x96, 0x8f, 0x56, 0x62, 0x10, 0x4a,
	0x38, 0x15, 0x44, 0x87, 0x50, 0xf9, 0x62, 0x07, 0x34, 0x96, 0x8b, 0x5c, 0x03, 0x1d, 0xe5, 0x9e,
	0x30, 0xf1, 0x89, 0x1d, 0x13, 0x2c, 0x04, 0xd0, 0x1b, 0xa8, 0x07, 0xe4, 0x8b, 0x25, 0xa4, 0x4b,
	0x5c, 0x7a, 0x6f, 0xd5, 0xfe, 0x07, 0x3b, 0xa0, 0xb8, 0x16, 0x90, 0x2f, 0x1f, 0xb8, 0xd2, 0x63,
	0xa8, 0x7b, 0x41, 0x4c, 0xed, 0xc0, 0x21, 0xb1, 0x5c, 0x3e, 0x28, 0x1d, 0x56, 0x70, 0x0e, 0xa0,
	0xef, 0xa0, 0x9d, 0xab, 0x5a, 0xc1, 0xfc, 0xf2, 0x13, 0x89, 0xe4, 0xca, 0x41, 0xe1, 0xb0, 0x84,
	0xa5, 0x9c, 0x31, 0xe6, 0x38, 0xfa, 0x0c, 0x28, 0xd5, 0xb4, 0x68, 0x68, 0x7d, 0x0e, 0x7d, 0x97,
	0x44, 0x72, 0x95, 0x07, 0xf2, 0xf6, 0xb6, 0x44, 0xf3, 0xea, 0x1c, 0x8d, 0x12, 0xe5, 0x69, 0xd8,
	0xe7, 0xaa, 0x5a, 0x40, 0xa3, 0x6b, 0x2c, 0x79, 0x4b, 0x70, 0xa7, 0x0b, 0xbb, 0x6b, 0x45, 0x91,
	0x04, 0xa5, 0x0b, 0x72, 0x2d, 0x17, 0x0e, 0x0a, 0x87, 0x15, 0xcc, 0x3e, 0xd1, 0x0e, 0x54, 0xae,
	0x6c, 0x7f, 0x4e, 0xe4, 0x22, 0xc7, 0x04, 0xf1, 0x43, 0xf1, 0x6d, 0x41, 0x99, 0x43, 0x55, 0x04,
	0x80, 0x5e, 0xb2, 0xa6, 0xf0, 0x42, 0x72, 0xcd, 0xf5, 0x25, 0x4e, 0x45, 0xd0, 0x8f, 0x50, 0xbb,
	0x24, 0xd4, 0x76, 0x6d, 0x6a, 0x73, 0xa3, 0x8d, 0xd7, 0xcf, 0xd6, 0xa5, 0xc6, 0x85, 0x4f, 0x12,
	0x41, 0x9c, 0xa9, 0x28, 0xff, 0x28, 0x40, 0x99, 0x15, 0xfe, 0xff, 0xf4, 0xfa, 0xc3, 0x8a, 0xd7,
	0x27, 0xeb, 0x3b, 0xbb, 0xea, 0x12, 0xed, 0x03, 0x38, 0x3e, 0xb1, 0x23, 0xfe, 0x30, 0xe4, 0xd2,
	0x41, 0xe1, 0xb0, 0x86, 0xeb, 0x1c, 0x61, 0x0a, 0xca, 0xb7, 0xd0, 0x5c, 0x54, 0x44, 0x7b, 0x50,
	0xb5, 0x1d, 0xea, 0x5d, 0x89, 0xb8, 0x6a, 0x38, 0xa1, 0x94, 0x7d, 0xa8, 0x4c, 0xc3, 0x0b, 0x12,
	0xb0, 0x9a, 0x52, 0xf6, 0xc1, 0xf9, 0x75, 0x2c, 0x08, 0xe5, 0xbf, 0x5b, 0xb0, 0xb5, 0x94, 0x36,
	0xf3, 0xec, 0xda, 0x94, 0x58, 0xb6, 0xeb, 0x12, 0x97, 0x8b, 0x97, 0x70, 0x9d, 0x21, 0x2a, 0x03,
	0xd0, 0x33, 0x68, 0x72, 0xf6, 0x7c, 0xc6, 0xfe, 0x71, 0x79, 0x62, 0x25, 0xdc, 0x60, 0xc4, 0xa9,
	0x80, 0xd0, 0x23, 0xa8, 0x7f, 0xf6, 0x7c, 0x62, 0xcd, 0x6c, 0x7a, 0xce, 0x43, 0xaf, 0xe3, 0x1a,
	0x03, 0x26, 0x36, 0x3d, 0x47, 0x08, 0xca, 0x4e, 0x18, 0x53, 0xb9, 0xcc, 0x7b, 0xcb, 0xbf, 0x59,
	0xf4, 0x7c, 0x3c, 0x63, 0xfe, 0x4a, 0x6b, 0x38, 0xa1, 0x50, 0x0b, 0x8a, 0x9e, 0x2b, 0x57, 0xb9,
	0x64, 0xd1, 0x73, 0x59, 0x68, 0xbe, 0x1d, 0x53, 0xcb, 0xb1, 0x9d, 0x73, 0x22, 0x6f, 0x88, 0xd0,
	0x18, 0xd2, 0x65, 0x00, 0xea, 0x43, 0xcd, 0xb1, 0x29, 0x39, 0x0b, 0xa3, 0x6b, 0xb9, 0x76, 0x50,
	0x38, 0x6c, 0xbd, 0x7e, 0x71, 0x6f, 0x97, 0x8f, 0xba, 0x89, 0x06, 0xce, 0x74, 0xd1, 0x53, 0x68,
	0x9c, 0x85, 0xb6, 0x9f, 0xce, 0x42, 0x9d, 0xfb, 0x07, 0x06, 0x89, 0x77, 0xcb, 0x8a, 0xe9, 0x7a,
	0x11, 0xbd, 0x96, 0x81, 0x87, 0x2b, 0x08, 0xa6, 0x76, 0x19, 0x5e, 0x91, 0x54, 0xad, 0x21, 0xd4,
	0x18, 0x94, 0xa8, 0xed, 0x03, 0xc4, 0x84, 0x5a, 0x91, 0x4d, 0xbd, 0xe0, 0x4c, 0x6e, 0x72, 0x7e,
	0x3d, 0x26, 0x14, 0x73, 0x00, 0x7d, 0x0d, 0x2d, 0x9e, 0x5d, 0x7c, 0x1d, 0x38, 0x16, 0xf5, 0x2e,
	0x89, 0xbc, 0xc9, 0x33, 0x6c, 0x32, 0xd4, 0xbc, 0x0e, 0x9c, 0xa9, 0x77, 0x49, 0xd0, 0x3b, 0xa8,
	0xcf, 0xe6, 0xd1, 0x99, 0x4d, 0x59, 0x96, 0x2d, 0x9e, 0xe5, 0xa3, 0xd5, 0x2c, 0x27, 0xa9, 0x08,
	0xce, 0xa5, 0xd1, 0x21, 0x48, 0xc2, 0x01, 0x0d, 0x9d, 0x0b, 0xcb, 0x39, 0x27, 0xce, 0x85, 0xbc,
	0xc5, 0x5d, 0x70, 0xc7, 0x26, 0x83, 0xbb, 0x0c, 0x45, 0xcf, 0x61, 0x33, 0xbc, 0x22, 0x91, 0xed,
	0xfb, 0x56, 0xec, 0x84, 0x11, 0x91, 0xa5, 0x83, 0xc2, 0x61, 0x11, 0x37, 0x13, 0xd0, 0x64, 0x18,
	0xcb, 0x37, 0x9e, 0x79, 0x01, 0xb1, 0xbe, 0x78, 0x2e, 0x3d, 0x97, 0xdb, 0x22, 0x5f, 0x0e, 0x7d,
	0x60, 0x08, 0x7b, 0x07, 0xb1, 0xed, 0x13, 0x8b, 0xf7, 0x1b, 0x71, 0x76, 0x8d, 0x01, 0x5d, 0xd6,
	0xf3, 0x87, 0xb0, 0xc1, 0x99, 0x9e, 0x2b, 0x6f, 0x73, 0x56, 0x95, 0x91, 0x23, 0xde, 0x64, 0xce,
	0x10, 0x15, 0xde, 0x15, 0x2f, 0x9f, 0x21, 0x3d, 0x5e, 0xe5, 0x94, 0x3d, 0x8b, 0x3c, 0x87, 0xc8,
	0x7b, 0x49, 0x11, 0x6d, 0x9f, 0x4c, 0x18, 0x80, 0xde, 0x24, 0xec, 0x98, 0xda, 0x94, 0xc8, 0x0f,
	0x79, 0x7d, 0x76, 0x16, 0x86, 0xd4, 0xb4, 0x7d, 0x62, 0x32, 0x9e, 0x50, 0xe2, 0x9f, 0xec, 0x4d,
	0x8b, 0xce, 0xd9, 0x9e, 0x3f, 0x8f, 0x88, 0xbc, 0xc3, 0xdf, 0x2c, 0xef, 0x66, 0x5f, 0x40, 0x59,
	0xed, 0x7c, 0x2f, 0xa6, 0x24, 0x10, 0xed, 0x91, 0xf3, 0xda, 0xe9, 0x1c, 0xe6, 0x0d, 0x7a, 0x08,
	0x1b, 0x8e, 0x2b, 0xde, 0xfe, 0x57, 0xdc, 0x4e, 0xd5, 0x71, 0xf9, 0xcb, 0x4f, 0xfb, 0xcb, 0x5d,
	0x71, 0x03, 0x9d, 0xbc, 0xbf, 0x27, 0xe1, 0x15, 0xe1, 0xea, 0x4f, 0xa1, 0x91, 0xed, 0x63, 0xcf,
	0x95, 0x1f, 0x89, 0xaa, 0xa6, 0xd0, 0xc8, 0x45, 0x2f, 0xa0, 0x1d, 0x10, 0xe2, 0xc6, 0x37, 0xda,
	0xf8, 0x98, 0x97, 0x69, 0x8b, 0x33, 0x16, 0xfa, 0xf8, 0x27, 0x28, 0x5f, 0x10, 0x32, 0x93, 0xf7,
	0x79, 0x1d, 0xbe, 0xbb, 0x7f, 0x1a, 0x8e, 0x09, 0x99, 0x89, 0xf2, 0x70, 0x45, 0xf4, 0x1e, 0x2a,
	0x97, 0x36, 0x75, 0xce, 0xe5, 0x27, 0xdc, 0xc2, 0xcb, 0xfb, 0x2d, 0x9c, 0x30, 0x71, 0x61, 0x42,
	0xa8, 0xa2, 0x97, 0x80, 0x9c, 0x79, 0x14, 0x91, 0x80, 0x5a, 0x0b, 0x9d, 0x7b, 0xca, 0x13, 0x93,
	0x12, 0x8e, 0x99, 0x35, 0xf0, 0x05, 0xb4, 0x73, 0xa9, 0x64, 0xcb, 0xc8, 0x07, 0xbc, 0x50, 0x5b,
	0x59, 0x9b, 0xc5, 0xa6, 0xc9, 0x27, 0xc6, 0x4e, 0x2b, 0xfa, 0x6c, 0x61, 0x62, 0xec, 0xa4, 0xa2,
	0xdf, 0x40, 0x8b, 0x0b, 0x78, 0x94, 0xb0, 0xd1, 0x0b, 0x03, 0x59, 0xe1, 0x52, 0x9b, 0x0c, 0x1d,
	0xa5, 0xa0, 0xf2, 0xaf, 0x32, 0xd4, 0xd2, 0x65, 0x80, 0x1a, 0xb0, 0x71, 0x3a, 0x3e, 0x1e, 0x1b,
	0x1f, 0xc6, 0xd2, 0x03, 0xb4, 0x09, 0xf5, 0xc9, 0x29, 0xee, 0x0e, 0x55, 0x53, 0xeb, 0x49, 0x05,
	0xd4, 0x02, 0x38, 0x1d, 0xeb, 0x23, 0x73, 0xaa, 0x8d, 0xb5, 0x9e, 0x54, 0x44, 0x00, 0x55, 0x73,
	0xaa, 0x0e, 0xb4, 0x9e, 0x54, 0x42, 0xdb, 0xb0, 0x35, 0xc1, 0x9a, 0x35, 0x1c, 0x0d, 0x86, 0x96,
	0xd9, 0x1d, 0x1a, 0x86, 0x2e, 0x7d, 0x85, 0xb6, 0xa0, 0xb1, 0x08, 0x74, 0x90, 0x04, 0x4d, 0x26,
	0xd5, 0xc7, 0x9a, 0x39, 0x3c, 0x51, 0xc7, 0x52, 0x19, 0x35, 0xa1, 0x96, 0x51, 0x95, 0x94, 0x6f,
	0x1a, 0x93, 0xe1, 0x89, 0x81, 0x35, 0xa9, 0xc9, 0xf8, 0x19, 0xb5, 0x99, 0xf2, 0x07, 0x58, 0xed,
	0x9d, 0xaa, 0x53, 0x4d, 0x02, 0xc6, 0xcf, 0xa8, 0x06, 0x73, 0xc8, 0xf8, 0x13, 0xc3, 0x9c, 0xf6,
	0x8c, 0xae, 0x54, 0x63, 0xe9, 0xa4, 0x44, 0x1d, 0xb5, 0x61, 0x93, 0x73, 0xb1, 0xd1, 0xd7, 0x4c,
	0xd3, 0xc0, 0x52, 0x95, 0x67, 0x98, 0x91, 0x1b, 0x68, 0x17, 0xda, 0x4c, 0xa2, 0x37, 0x32, 0xa7,
	0xa3, 0xf1, 0xe0, 0x74, 0x64, 0x0e, 0xb5, 0x9e, 0xf4, 0x84, 0x29, 0xde, 0x84, 0x9e, 0x26, 0xf9,
	0x4e, 0x54, 0xac, 0x59, 0x53, 0xc3, 0x32, 0x35, 0x5d, 0x97, 0xb6, 0x19, 0xa8, 0x9a, 0xa6, 0x66,
	0x9a, 0x56, 0xdf, 0xc0, 0x96, 0xa9, 0xea, 0x9a, 0x24, 0x23, 0x04, 0x2d, 0x51, 0xa5, 0x4c, 0xb0,
	0xc5, 0x0c, 0xe2, 0xd1, 0xc4, 0x9a, 0x0e, 0xb5, 0xb1, 0x80, 0x76, 0x51, 0x0d, 0xca, 0xa6, 0xa1,
	0xf7, 0xa4, 0x2d, 0x96, 0x24, 0xfb, 0xb2, 0x54, 0xdc, 0x1d, 0x8e, 0x7e, 0xd6, 0xa4, 0x3d, 0x66,
	0x82, 0x97, 0x3d, 0x37, 0xf1, 0x30, 0x93, 0x32, 0xfa, 0x7d, 0x7d, 0x34, 0xd6, 0xa4, 0x47, 0xac,
	0x3d, 0xe6, 0x54, 0xd5, 0x35, 0xe1, 0xf8, 0x31, 0xcb, 0xbd, 0x37, 0x1a, 0x8c, 0xa6, 0xaa, 0x2e,
	0x49, 0xac, 0x32, 0x03, 0xc3, 0x18, 0xe8, 0x9a, 0x35, 0xd1, 0xd5, 0x8f, 0x12, 0x62, 0xcd, 0x13,
	0xb1, 0x4a, 0x6d, 0x56, 0x85, 0xb1, 0x61, 0xe9, 0xea, 0x7b, 0x4d, 0x37, 0xa5, 0x1d, 0x5e, 0x34,
	0x15, 0x6b, 0xe3, 0xa9, 0x29, 0xed, 0x2b, 0xef, 0xa0, 0x9e, 0xcd, 0x06, 0x73, 0x7a, 0xac, 0x69,
	0x13, 0x2b, 0x7f, 0x22, 0x2d, 0x80, 0xb1, 0x31, 0xb5, 0x18, 0xaa, 0x61, 0xa9, 0xc0, 0xcc, 0x26,
	0xdf, 0x45, 0x65, 0x02, 0x90, 0x0f, 0x05, 0xcb, 0xf9, 0x44, 0x9d, 0x76, 0x87, 0x0b, 0xca, 0x4d,
	0xa8, 0x8d, 0x0d, 0x8b, 0xa3, 0x52, 0x81, 0xb7, 0x47, 0xc5, 0xd3, 0x91, 0xaa, 0x27, 0x50, 0x91,
	0x59, 0xef, 0x9f, 0xea, 0x29, 0x5d, 0x52, 0xfe, 0x53, 0x80, 0xf6, 0x80, 0x50, 0x71, 0x0a, 0xc5,
	0x98, 0xfc, 0x32, 0x27, 0x31, 0x45, 0xdf, 0x43, 0xf5, 0xb3, 0xe7, 0x53, 0x12, 0x25, 0xb7, 0xc9,
	0xed, 0x67, 0x6a, 0x22, 0xc7, 0x7e, 0xc7, 0x3e, 0x87, 0x91, 0x23, 0x0e, 0xad, 0x1a, 0x16, 0x04,
	0x43, 0x63, 0x1a, 0x79, 0xb3, 0xe4, 0xea, 0x10, 0x04, 0xdb, 0xbb, 0x7c, 0x71, 0x09, 0x56, 0x59,
	0xac, 0x65, 0x86, 0x98, 0x9c, 0xbd, 0x07, 0x55, 0xc7, 0xf6, 0xfd, 0xe4, 0xd0, 0x64, 0x4b, 0x8f,
	0x53, 0xca, 0xdf, 0x0b, 0x80, 0x16, 0x43, 0x8d, 0x67, 0x61, 0x10, 0x93, 0xdf, 0x74, 0x53, 0xbf,
	0x05, 0xd9, 0x0b, 0x28, 0x89, 0x02, 0xdb, 0xb7, 0x66, 0x51, 0xe8, 0x90, 0x38, 0xf6, 0x82, 0x33,
	0x31, 0xf7, 0xe2, 0x0a, 0xd9, 0x4b, 0xf9, 0x93, 0x8c, 0xcd, 0x36, 0x80, 0xa2, 0xc2, 0xd6, 0x80,
	0x50, 0x7e, 0x3a, 0xa7, 0xc5, 0x3a, 0x5a, 0x2a, 0xd6, 0x6d, 0x37, 0x77, 0x22, 0xa5, 0xfc, 0x04,
	0x52, 0x6e, 0x22, 0x49, 0xe2, 0x65, 0x7a, 0xe4, 0x17, 0xee, 0x3c, 0xdb, 0x85, 0x90, 0xf2, 0x37,
	0xd8, 0x16, 0x6b, 0x2b, 0xc9, 0x2b, 0xef, 0x5a, 0xb2, 0xe4, 0xee, 0xed, 0x9a, 0x90, 0x63, 0xc7,
	0x7f, 0x24, 0x94, 0xc3, 0x88, 0x27, 0x5e, 0xc7, 0x39, 0xc0, 0x7e, 0x7e, 0x82, 0xd0, 0x8a, 0x89,
	0xef, 0x27, 0xfd, 0xab, 0x06, 0xa1, 0x49, 0x7c, 0x5f, 0x39, 0x86, 0xdd, 0x45, 0xff, 0x37, 0x7a,
	0x91, 0x1e, 0x73, 0xf7, 0x85, 0x90, 0x0a, 0x2a, 0x7f, 0x81, 0xb6, 0x30, 0xc6, 0x33, 0xcc, 0x6b,
	0x7a, 0x23, 0x95, 0x5b, 0x6b, 0x9a, 0x24, 0xb2, 0x07, 0xd5, 0x88, 0xb0, 0x27, 0x94, 0xbc, 0xbf,
	0x84, 0x52, 0xfa, 0x80, 0x16, 0x8d, 0x27, 0x61, 0x7e, 0xbf, 0x1c, 0xe6, 0x6d, 0xe6, 0xb3, 0x20,
	0xbb, 0x20, 0xa9, 0xae, 0x7b, 0xb3, 0xdc, 0xaf, 0xa0, 0x4a, 0x43, 0x76, 0xdb, 0xde, 0x9b, 0x6b,
	0x85, 0x86, 0xaa, 0xcb, 0x8c, 0xb4, 0x17, 0x8c, 0x24, 0xb1, 0x1c, 0x41, 0x45, 0x9c, 0xc7, 0xc5,
	0xfb, 0x8c, 0x70, 0x31, 0xe5, 0x31, 0x74, 0xb2, 0x21, 0xc8, 0xff, 0xef, 0x94, 0xc4, 0xa4, 0xfc,
	0x04, 0x8f, 0xd6, 0x72, 0x13, 0x67, 0xcf, 0xa0, 0xb9, 0x70, 0x11, 0x88, 0xd7, 0x56, 0xc1, 0x8d,
	0xfc, 0x24, 0x88, 0x95, 0x3f, 0xc2, 0x76, 0x8f, 0xf8, 0x64, 0xf9, 0x6d, 0x2d, 0xdd, 0x12, 0x85,
	0xe5, 0x5b, 0x42, 0xd9, 0x83, 0x9d, 0x9b, 0x7a, 0xc2, 0xa5, 0xf2, 0x23, 0x6c, 0xff, 0x79, 0x4e,
	0xa2, 0xeb, 0xa5, 0x0d, 0xb3, 0x0f, 0x75, 0x71, 0xdc, 0x66, 0xd6, 0x86, 0x0f, 0x70, 0x4d, 0x40,
	0x23, 0xf7, 0xfd, 0x06, 0x54, 0x7e, 0x61, 0x5a, 0xca, 0x3b, 0xd8, 0xb9, 0xa9, 0xfe, 0xab, 0x33,
	0x79, 0x11, 0x41, 0x3d, 0xbb, 0x5d, 0x6f, 0xfe, 0x0a, 0x23, 0x68, 0x8d, 0x0d, 0x6b, 0x60, 0xa8,
	0xba, 0xd5, 0x37, 0xf4, 0x1e, 0x5f, 0xb3, 0xbb, 0xd0, 0x1e, 0x6b, 0x5a, 0xcf, 0xb4, 0xcc, 0xa9,
	0xd1, 0x3d, 0xb6, 0xba, 0x43, 0xad, 0x7b, 0x2c, 0x15, 0xd9, 0x7e, 0x16, 0x70, 0xb2, 0xcb, 0xcb,
	0x7c, 0xb5, 0x73, 0x04, 0x8f, 0x26, 0x52, 0x85, 0x6d, 0x5c, 0x55, 0xd7, 0xad, 0x81, 0x61, 0xf4,
	0xa4, 0xd2, 0xeb, 0x7f, 0x56, 0xe1, 0xe1, 0x72, 0xf5, 0x4d, 0x12, 0x5d, 0xb1, 0x73, 0xe4, 0x23,
	0x40, 0xbe, 0xbe, 0xd0, 0xf3, 0xd5, 0x46, 0xaf, 0xec, 0xe1, 0xce, 0xd7, 0x77, 0x0b, 0x25, 0x25,
	0x7e, 0x80, 0x4c, 0xa8, 0xa5, 0x2b, 0x05, 0x3d, 0x5b, 0xab, 0xb3, 0xb8, 0xb1, 0x3a, 0xca, 0x5d,
	0x22, 0x99, 0xd1, 0xbf, 0x42, 0x73, 0x71, 0xca, 0xd1, 0x37, 0xab, 0x5a, 0x6b, 0xb6, 0x50, 0xe7,
	0x77, 0x77, 0x8b, 0x2d, 0x7a, 0xf8, 0x08, 0x90, 0x4f, 0xe7, 0xba, 0x8a, 0xac, 0x2c, 0x86, 0x75,
	0x15, 0x59, 0x1d, 0x70, 0xe5, 0x01, 0xfa, 0x19, 0xea, 0xd9, 0xac, 0xa1, 0x35, 0xf9, 0x2e, 0x4f,
	0x73, 0xe7, 0xf9, 0x9d, 0x32, 0x99, 0x5d, 0x0a, 0xdb, 0x6b, 0x06, 0x0c, 0xbd, 0xbc, 0xa3, 0x51,
	0x2b, 0x53, 0xda, 0xf9, 0xfd, 0xaf, 0x94, 0xce, 0xbc, 0x5a, 0xd0, 0x5c, 0x1c, 0xae, 0x75, 0xad,
	0x58, 0x33, 0xb4, 0x9d, 0x6f, 0xef, 0x13, 0x5b, 0x74, 0xb0, 0x38, 0x66, 0xeb, 0x1c, 0xac, 0x99,
	0xe2, 0x75, 0x0e, 0xd6, 0x4d, 0xab, 0xf2, 0xe0, 0x53, 0x95, 0xff, 0x55, 0xec, 0xcd, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x10, 0xfc, 0x0a, 0xeb, 0x74, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecordCollectionServiceClient is the client API for RecordCollectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordCollectionServiceClient interface {
	GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (*GetRecordsResponse, error)
	GetWants(ctx context.Context, in *GetWantsRequest, opts ...grpc.CallOption) (*GetWantsResponse, error)
	UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*UpdateRecordsResponse, error)
	UpdateWant(ctx context.Context, in *UpdateWantRequest, opts ...grpc.CallOption) (*UpdateWantResponse, error)
	AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error)
	GetRecordCollection(ctx context.Context, in *GetRecordCollectionRequest, opts ...grpc.CallOption) (*GetRecordCollectionResponse, error)
	DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error)
	QueryRecords(ctx context.Context, in *QueryRecordsRequest, opts ...grpc.CallOption) (*QueryRecordsResponse, error)
}

type recordCollectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecordCollectionServiceClient(cc *grpc.ClientConn) RecordCollectionServiceClient {
	return &recordCollectionServiceClient{cc}
}

func (c *recordCollectionServiceClient) GetRecords(ctx context.Context, in *GetRecordsRequest, opts ...grpc.CallOption) (*GetRecordsResponse, error) {
	out := new(GetRecordsResponse)
	err := c.cc.Invoke(ctx, "/recordcollection.RecordCollectionService/GetRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordCollectionServiceClient) GetWants(ctx context.Context, in *GetWantsRequest, opts ...grpc.CallOption) (*GetWantsResponse, error) {
	out := new(GetWantsResponse)
	err := c.cc.Invoke(ctx, "/recordcollection.RecordCollectionService/GetWants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordCollectionServiceClient) UpdateRecord(ctx context.Context, in *UpdateRecordRequest, opts ...grpc.CallOption) (*UpdateRecordsResponse, error) {
	out := new(UpdateRecordsResponse)
	err := c.cc.Invoke(ctx, "/recordcollection.RecordCollectionService/UpdateRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordCollectionServiceClient) UpdateWant(ctx context.Context, in *UpdateWantRequest, opts ...grpc.CallOption) (*UpdateWantResponse, error) {
	out := new(UpdateWantResponse)
	err := c.cc.Invoke(ctx, "/recordcollection.RecordCollectionService/UpdateWant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordCollectionServiceClient) AddRecord(ctx context.Context, in *AddRecordRequest, opts ...grpc.CallOption) (*AddRecordResponse, error) {
	out := new(AddRecordResponse)
	err := c.cc.Invoke(ctx, "/recordcollection.RecordCollectionService/AddRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordCollectionServiceClient) GetRecordCollection(ctx context.Context, in *GetRecordCollectionRequest, opts ...grpc.CallOption) (*GetRecordCollectionResponse, error) {
	out := new(GetRecordCollectionResponse)
	err := c.cc.Invoke(ctx, "/recordcollection.RecordCollectionService/GetRecordCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordCollectionServiceClient) DeleteRecord(ctx context.Context, in *DeleteRecordRequest, opts ...grpc.CallOption) (*DeleteRecordResponse, error) {
	out := new(DeleteRecordResponse)
	err := c.cc.Invoke(ctx, "/recordcollection.RecordCollectionService/DeleteRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordCollectionServiceClient) QueryRecords(ctx context.Context, in *QueryRecordsRequest, opts ...grpc.CallOption) (*QueryRecordsResponse, error) {
	out := new(QueryRecordsResponse)
	err := c.cc.Invoke(ctx, "/recordcollection.RecordCollectionService/QueryRecords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordCollectionServiceServer is the server API for RecordCollectionService service.
type RecordCollectionServiceServer interface {
	GetRecords(context.Context, *GetRecordsRequest) (*GetRecordsResponse, error)
	GetWants(context.Context, *GetWantsRequest) (*GetWantsResponse, error)
	UpdateRecord(context.Context, *UpdateRecordRequest) (*UpdateRecordsResponse, error)
	UpdateWant(context.Context, *UpdateWantRequest) (*UpdateWantResponse, error)
	AddRecord(context.Context, *AddRecordRequest) (*AddRecordResponse, error)
	GetRecordCollection(context.Context, *GetRecordCollectionRequest) (*GetRecordCollectionResponse, error)
	DeleteRecord(context.Context, *DeleteRecordRequest) (*DeleteRecordResponse, error)
	QueryRecords(context.Context, *QueryRecordsRequest) (*QueryRecordsResponse, error)
}

func RegisterRecordCollectionServiceServer(s *grpc.Server, srv RecordCollectionServiceServer) {
	s.RegisterService(&_RecordCollectionService_serviceDesc, srv)
}

func _RecordCollectionService_GetRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordCollectionServiceServer).GetRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordcollection.RecordCollectionService/GetRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordCollectionServiceServer).GetRecords(ctx, req.(*GetRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordCollectionService_GetWants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordCollectionServiceServer).GetWants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordcollection.RecordCollectionService/GetWants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordCollectionServiceServer).GetWants(ctx, req.(*GetWantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordCollectionService_UpdateRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordCollectionServiceServer).UpdateRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordcollection.RecordCollectionService/UpdateRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordCollectionServiceServer).UpdateRecord(ctx, req.(*UpdateRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordCollectionService_UpdateWant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordCollectionServiceServer).UpdateWant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordcollection.RecordCollectionService/UpdateWant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordCollectionServiceServer).UpdateWant(ctx, req.(*UpdateWantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordCollectionService_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordCollectionServiceServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordcollection.RecordCollectionService/AddRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordCollectionServiceServer).AddRecord(ctx, req.(*AddRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordCollectionService_GetRecordCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecordCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordCollectionServiceServer).GetRecordCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordcollection.RecordCollectionService/GetRecordCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordCollectionServiceServer).GetRecordCollection(ctx, req.(*GetRecordCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordCollectionService_DeleteRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordCollectionServiceServer).DeleteRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordcollection.RecordCollectionService/DeleteRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordCollectionServiceServer).DeleteRecord(ctx, req.(*DeleteRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordCollectionService_QueryRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordCollectionServiceServer).QueryRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recordcollection.RecordCollectionService/QueryRecords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordCollectionServiceServer).QueryRecords(ctx, req.(*QueryRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecordCollectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recordcollection.RecordCollectionService",
	HandlerType: (*RecordCollectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecords",
			Handler:    _RecordCollectionService_GetRecords_Handler,
		},
		{
			MethodName: "GetWants",
			Handler:    _RecordCollectionService_GetWants_Handler,
		},
		{
			MethodName: "UpdateRecord",
			Handler:    _RecordCollectionService_UpdateRecord_Handler,
		},
		{
			MethodName: "UpdateWant",
			Handler:    _RecordCollectionService_UpdateWant_Handler,
		},
		{
			MethodName: "AddRecord",
			Handler:    _RecordCollectionService_AddRecord_Handler,
		},
		{
			MethodName: "GetRecordCollection",
			Handler:    _RecordCollectionService_GetRecordCollection_Handler,
		},
		{
			MethodName: "DeleteRecord",
			Handler:    _RecordCollectionService_DeleteRecord_Handler,
		},
		{
			MethodName: "QueryRecords",
			Handler:    _RecordCollectionService_QueryRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recordcollection.proto",
}
