// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: v1/sale_description.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Grading int32

const (
	Grading_GRADING_UNSPECIFIED    Grading = 0
	Grading_GRADING_MINT           Grading = 1
	Grading_GRADING_NEAR_MINT      Grading = 2
	Grading_GRADING_VERY_GOOD_PLUS Grading = 3
	Grading_GRADING_VERY_GOOD      Grading = 4
	Grading_GRADING_GOOD_PLUS      Grading = 5
	Grading_GRADING_GOOD           Grading = 6
	Grading_GRADING_FAIR           Grading = 7
	Grading_GRADING_POOR           Grading = 8
)

// Enum value maps for Grading.
var (
	Grading_name = map[int32]string{
		0: "GRADING_UNSPECIFIED",
		1: "GRADING_MINT",
		2: "GRADING_NEAR_MINT",
		3: "GRADING_VERY_GOOD_PLUS",
		4: "GRADING_VERY_GOOD",
		5: "GRADING_GOOD_PLUS",
		6: "GRADING_GOOD",
		7: "GRADING_FAIR",
		8: "GRADING_POOR",
	}
	Grading_value = map[string]int32{
		"GRADING_UNSPECIFIED":    0,
		"GRADING_MINT":           1,
		"GRADING_NEAR_MINT":      2,
		"GRADING_VERY_GOOD_PLUS": 3,
		"GRADING_VERY_GOOD":      4,
		"GRADING_GOOD_PLUS":      5,
		"GRADING_GOOD":           6,
		"GRADING_FAIR":           7,
		"GRADING_POOR":           8,
	}
)

func (x Grading) Enum() *Grading {
	p := new(Grading)
	*p = x
	return p
}

func (x Grading) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Grading) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_sale_description_proto_enumTypes[0].Descriptor()
}

func (Grading) Type() protoreflect.EnumType {
	return &file_v1_sale_description_proto_enumTypes[0]
}

func (x Grading) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Grading.Descriptor instead.
func (Grading) EnumDescriptor() ([]byte, []int) {
	return file_v1_sale_description_proto_rawDescGZIP(), []int{0}
}

type GenerateDescriptionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RecordTitle     string                 `protobuf:"bytes,1,opt,name=record_title,json=recordTitle,proto3" json:"record_title,omitempty"`
	Artist          string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	MediaCondition  Grading                `protobuf:"varint,3,opt,name=media_condition,json=mediaCondition,proto3,enum=sale_description.v1.Grading" json:"media_condition,omitempty"`
	SleeveCondition Grading                `protobuf:"varint,4,opt,name=sleeve_condition,json=sleeveCondition,proto3,enum=sale_description.v1.Grading" json:"sleeve_condition,omitempty"`
	UserNotes       string                 `protobuf:"bytes,5,opt,name=user_notes,json=userNotes,proto3" json:"user_notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateDescriptionRequest) Reset() {
	*x = GenerateDescriptionRequest{}
	mi := &file_v1_sale_description_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDescriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDescriptionRequest) ProtoMessage() {}

func (x *GenerateDescriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sale_description_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDescriptionRequest.ProtoReflect.Descriptor instead.
func (*GenerateDescriptionRequest) Descriptor() ([]byte, []int) {
	return file_v1_sale_description_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateDescriptionRequest) GetRecordTitle() string {
	if x != nil {
		return x.RecordTitle
	}
	return ""
}

func (x *GenerateDescriptionRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *GenerateDescriptionRequest) GetMediaCondition() Grading {
	if x != nil {
		return x.MediaCondition
	}
	return Grading_GRADING_UNSPECIFIED
}

func (x *GenerateDescriptionRequest) GetSleeveCondition() Grading {
	if x != nil {
		return x.SleeveCondition
	}
	return Grading_GRADING_UNSPECIFIED
}

func (x *GenerateDescriptionRequest) GetUserNotes() string {
	if x != nil {
		return x.UserNotes
	}
	return ""
}

type GenerateDescriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDescriptionResponse) Reset() {
	*x = GenerateDescriptionResponse{}
	mi := &file_v1_sale_description_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDescriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDescriptionResponse) ProtoMessage() {}

func (x *GenerateDescriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sale_description_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDescriptionResponse.ProtoReflect.Descriptor instead.
func (*GenerateDescriptionResponse) Descriptor() ([]byte, []int) {
	return file_v1_sale_description_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateDescriptionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_v1_sale_description_proto protoreflect.FileDescriptor

const file_v1_sale_description_proto_rawDesc = "" +
	"\n" +
	"\x19v1/sale_description.proto\x12\x13sale_description.v1\"\x86\x02\n" +
	"\x1aGenerateDescriptionRequest\x12!\n" +
	"\frecord_title\x18\x01 \x01(\tR\vrecordTitle\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12E\n" +
	"\x0fmedia_condition\x18\x03 \x01(\x0e2\x1c.sale_description.v1.GradingR\x0emediaCondition\x12G\n" +
	"\x10sleeve_condition\x18\x04 \x01(\x0e2\x1c.sale_description.v1.GradingR\x0fsleeveCondition\x12\x1d\n" +
	"\n" +
	"user_notes\x18\x05 \x01(\tR\tuserNotes\"?\n" +
	"\x1bGenerateDescriptionResponse\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription*\xcb\x01\n" +
	"\aGrading\x12\x17\n" +
	"\x13GRADING_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fGRADING_MINT\x10\x01\x12\x15\n" +
	"\x11GRADING_NEAR_MINT\x10\x02\x12\x1a\n" +
	"\x16GRADING_VERY_GOOD_PLUS\x10\x03\x12\x15\n" +
	"\x11GRADING_VERY_GOOD\x10\x04\x12\x15\n" +
	"\x11GRADING_GOOD_PLUS\x10\x05\x12\x10\n" +
	"\fGRADING_GOOD\x10\x06\x12\x10\n" +
	"\fGRADING_FAIR\x10\a\x12\x10\n" +
	"\fGRADING_POOR\x10\b2\x92\x01\n" +
	"\x16SaleDescriptionService\x12x\n" +
	"\x13GenerateDescription\x12/.sale_description.v1.GenerateDescriptionRequest\x1a0.sale_description.v1.GenerateDescriptionResponseBBZ@github.com/brotherlogic/sale-description-generator/api/gen/v1;v1b\x06proto3"

var (
	file_v1_sale_description_proto_rawDescOnce sync.Once
	file_v1_sale_description_proto_rawDescData []byte
)

func file_v1_sale_description_proto_rawDescGZIP() []byte {
	file_v1_sale_description_proto_rawDescOnce.Do(func() {
		file_v1_sale_description_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_sale_description_proto_rawDesc), len(file_v1_sale_description_proto_rawDesc)))
	})
	return file_v1_sale_description_proto_rawDescData
}

var file_v1_sale_description_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_sale_description_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_sale_description_proto_goTypes = []any{
	(Grading)(0),                        // 0: sale_description.v1.Grading
	(*GenerateDescriptionRequest)(nil),  // 1: sale_description.v1.GenerateDescriptionRequest
	(*GenerateDescriptionResponse)(nil), // 2: sale_description.v1.GenerateDescriptionResponse
}
var file_v1_sale_description_proto_depIdxs = []int32{
	0, // 0: sale_description.v1.GenerateDescriptionRequest.media_condition:type_name -> sale_description.v1.Grading
	0, // 1: sale_description.v1.GenerateDescriptionRequest.sleeve_condition:type_name -> sale_description.v1.Grading
	1, // 2: sale_description.v1.SaleDescriptionService.GenerateDescription:input_type -> sale_description.v1.GenerateDescriptionRequest
	2, // 3: sale_description.v1.SaleDescriptionService.GenerateDescription:output_type -> sale_description.v1.GenerateDescriptionResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_sale_description_proto_init() }
func file_v1_sale_description_proto_init() {
	if File_v1_sale_description_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_sale_description_proto_rawDesc), len(file_v1_sale_description_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_sale_description_proto_goTypes,
		DependencyIndexes: file_v1_sale_description_proto_depIdxs,
		EnumInfos:         file_v1_sale_description_proto_enumTypes,
		MessageInfos:      file_v1_sale_description_proto_msgTypes,
	}.Build()
	File_v1_sale_description_proto = out.File
	file_v1_sale_description_proto_goTypes = nil
	file_v1_sale_description_proto_depIdxs = nil
}
