// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: v1/sale_description.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SaleDescriptionService_GenerateDescription_FullMethodName = "/sale_description.v1.SaleDescriptionService/GenerateDescription"
)

// SaleDescriptionServiceClient is the client API for SaleDescriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaleDescriptionServiceClient interface {
	GenerateDescription(ctx context.Context, in *GenerateDescriptionRequest, opts ...grpc.CallOption) (*GenerateDescriptionResponse, error)
}

type saleDescriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSaleDescriptionServiceClient(cc grpc.ClientConnInterface) SaleDescriptionServiceClient {
	return &saleDescriptionServiceClient{cc}
}

func (c *saleDescriptionServiceClient) GenerateDescription(ctx context.Context, in *GenerateDescriptionRequest, opts ...grpc.CallOption) (*GenerateDescriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDescriptionResponse)
	err := c.cc.Invoke(ctx, SaleDescriptionService_GenerateDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaleDescriptionServiceServer is the server API for SaleDescriptionService service.
// All implementations should embed UnimplementedSaleDescriptionServiceServer
// for forward compatibility.
type SaleDescriptionServiceServer interface {
	GenerateDescription(context.Context, *GenerateDescriptionRequest) (*GenerateDescriptionResponse, error)
}

// UnimplementedSaleDescriptionServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSaleDescriptionServiceServer struct{}

func (UnimplementedSaleDescriptionServiceServer) GenerateDescription(context.Context, *GenerateDescriptionRequest) (*GenerateDescriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateDescription not implemented")
}
func (UnimplementedSaleDescriptionServiceServer) testEmbeddedByValue() {}

// UnsafeSaleDescriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaleDescriptionServiceServer will
// result in compilation errors.
type UnsafeSaleDescriptionServiceServer interface {
	mustEmbedUnimplementedSaleDescriptionServiceServer()
}

func RegisterSaleDescriptionServiceServer(s grpc.ServiceRegistrar, srv SaleDescriptionServiceServer) {
	// If the following call panics, it indicates UnimplementedSaleDescriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SaleDescriptionService_ServiceDesc, srv)
}

func _SaleDescriptionService_GenerateDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleDescriptionServiceServer).GenerateDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaleDescriptionService_GenerateDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleDescriptionServiceServer).GenerateDescription(ctx, req.(*GenerateDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaleDescriptionService_ServiceDesc is the grpc.ServiceDesc for SaleDescriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaleDescriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sale_description.v1.SaleDescriptionService",
	HandlerType: (*SaleDescriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateDescription",
			Handler:    _SaleDescriptionService_GenerateDescription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/sale_description.proto",
}
