name: RunBasic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    name: basic_assess
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
     
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19.2'
   
    - name: Check for logs
      run: ./look_for_logs.sh

    - name: Run build
      run: go build github.com/${GITHUB_REPOSITORY}

    - name: Run test
      run: go test github.com/${GITHUB_REPOSITORY} -coverprofile=profile.cov
    
    - name: Coveralls
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
        ignore: recordcollection.go
    
    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3